#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me permanently redirect to another page.

REDIRECT_301="\\\tlocation /redirect_me {\n\t\t return 301 https://youtube.com;\n\t}\n" #variable for the config

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "53i $REDIRECT_301" /etc/nginx/sites-enabled/default # add config at line 53

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
