#!/usr/bin/env bash
# Install and configue HAproxy so that it send traffic to web-01 and web-02
# Requests distributed using roundrobin algorithm

CONFIG="\\\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\toption forwardfor\n\tserver 65311-web-01 54.164.8.29:80 check\n\tserver 65311-web-02 100.25.161.14:80 check\n"

if which haproxy >/dev/null 2>&1; then
	sudo apt-get -y purge --auto-remove haproxy
fi

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6.\*

# Make sure HAproxy can be managed via an init script
# sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure to include roundrobin and two servers
sudo sed -i "\$a $CONFIG" /etc/haproxy/haproxy.cfg

# Make sure HAproxy can be managed via an init script
sudo systemctl enable haproxy.service
sudo service haproxy restart
