#!/usr/bin/env bash
# Scripts that uses if, elif, and else statements

x=1
while [ "$x" -le 10 ]; do
	if [ "$x" -eq 4 ]; then
		echo "bad luck"
	elif [ "$x" -eq 8 ]; then
		echo "bad luck"
	else
		echo "Best School"
	fi
	x=$((x + 1))
done
