#!/usr/bin/env bash
# displays The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is displayed
#+ e.g 1-for_best_school is displayed as for_best_school

for f in * ; do
	echo "$f" | cut -f 2- -d '-'
done
