#!/usr/bin/env bash
# script that uses nested if statements
#+ to check the existence, and type of a file
#+ also checks if the file is empty or not

file="school"
if [ -e $file ]; then
    echo "$file file exists"

    if [ -s $file ]; then
	echo "$file file is not empty"
    else
	echo "$file file is empty"
    fi

    if [ -f $file ]; then
	echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
